2024-07-09 19:45:15,817 - DEBUG - Using selector: KqueueSelector
2024-07-09 19:45:16,944 - INFO - https://dribbble.com has started
2024-07-09 19:45:16,944 - DEBUG - All parameters for https://dribbble.com:
Bs4Config(name='https://dribbble.com', url='https://dribbble.com/jobs?anywhere=true&keyword=&page=', pages_to_crawl=1, start_point=1, strategy='main', follow_link='yes', inner_link_tag='.flushed .container-small.job-details-page-container .main-content-container .margin-t-16.job-details-description', elements_path={'jobs_path': '.job-list-item', 'title_path': '.job-details-container .job-title-company-container .job-title.job-board-job-title', 'link_path': '.job-link', 'location_path': '.job-additional-details-container .job-details .location-container.job-board-job-location', 'description_path': '.job-details-container .job-title-company-container .job-role'})
2024-07-09 19:45:16,944 - ERROR - AttributeError occurred before deploying crawling strategy on https://dribbble.com/jobs?anywhere=true&keyword=&page=1.

type object 'Bs4Config' has no attribute 'url'
Traceback (most recent call last):
  File "/Users/work/DevBox/JobsCrawler/src/crawlers/async_bs4.py", line 303, in async_bs4_crawl
    html = await fetch_func(session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/work/DevBox/JobsCrawler/src/crawler.py", line 101, in __fetch
    async with session.get(self.config.url, headers=random_user_agent) as response:
                           ^^^^^^^^^^^^^^^
AttributeError: type object 'Bs4Config' has no attribute 'url'
2024-07-09 19:45:16,947 - INFO - https://www.python.org has started
2024-07-09 19:45:16,947 - DEBUG - All parameters for https://www.python.org:
Bs4Config(name='https://www.python.org', url='https://www.python.org/jobs/?page=', pages_to_crawl=1, start_point=1, strategy='main', follow_link='yes', inner_link_tag='.content-wrapper .container .main-content.with-right-sidebar .text .job-description', elements_path={'jobs_path': '.list-recent-jobs.list-row-container.menu li', 'title_path': '.listing-company-name a', 'link_path': '.listing-company-name a', 'description_path': '.listing-job-type', 'location_path': '.listing-location a'})
2024-07-09 19:45:16,947 - ERROR - AttributeError occurred before deploying crawling strategy on https://www.python.org/jobs/?page=1.

type object 'Bs4Config' has no attribute 'url'
Traceback (most recent call last):
  File "/Users/work/DevBox/JobsCrawler/src/crawlers/async_bs4.py", line 303, in async_bs4_crawl
    html = await fetch_func(session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/work/DevBox/JobsCrawler/src/crawler.py", line 101, in __fetch
    async with session.get(self.config.url, headers=random_user_agent) as response:
                           ^^^^^^^^^^^^^^^
AttributeError: type object 'Bs4Config' has no attribute 'url'
2024-07-09 19:45:16,947 - INFO -  has started
2024-07-09 19:45:16,947 - DEBUG - All parameters for :
Bs4Config(name='', url='https://www.fossjobs.net/jobs-worldwide/?page=', pages_to_crawl=1, start_point=1, strategy='main', follow_link='yes', inner_link_tag='.container .columns .column.is-9 .box.content .job-description', elements_path={'jobs_path': '.container .columns .column.is-9 .box.content .post', 'title_path': 'h2 a', 'link_path': 'h2 a', 'location_path': '.media .media-content .content', 'description_path': '.media .media-content .content'})
2024-07-09 19:45:16,947 - ERROR - AttributeError occurred before deploying crawling strategy on https://www.fossjobs.net/jobs-worldwide/?page=1.

type object 'Bs4Config' has no attribute 'url'
Traceback (most recent call last):
  File "/Users/work/DevBox/JobsCrawler/src/crawlers/async_bs4.py", line 303, in async_bs4_crawl
    html = await fetch_func(session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/work/DevBox/JobsCrawler/src/crawler.py", line 101, in __fetch
    async with session.get(self.config.url, headers=random_user_agent) as response:
                           ^^^^^^^^^^^^^^^
AttributeError: type object 'Bs4Config' has no attribute 'url'
2024-07-09 19:45:16,948 - INFO - https://vuejobs.com has started
2024-07-09 19:45:16,948 - DEBUG - All parameters for https://vuejobs.com:
Bs4Config(name='https://vuejobs.com', url='https://vuejobs.com/jobs/?page=', pages_to_crawl=1, start_point=1, strategy='container', follow_link='yes', inner_link_tag='.lg\\:pb-12 .py-8.lg\\:py-12 .container .order-2.lg\\:order.lg\\:col-span-5 .prose.max-w-full.mt-6.prose-lg', elements_path={'jobs_path': '.grid.gap-y-4', 'title_path': 'a .flex.flex-col.justify-center.md\\:flex-row.md\\:justify-start.md\\:items-center .flex.items-center .ml-3', 'link_path': 'a', 'location_path': 'a .text-xs.mt-3.flex.gap-x-4.gap-y-1.flex-wrap.items-center.md\\:gap-2', 'description_path': 'a .text-xs.mt-3.flex.gap-x-4.gap-y-1.flex-wrap.items-center.md\\:gap-2'})
2024-07-09 19:45:16,948 - ERROR - AttributeError occurred before deploying crawling strategy on https://vuejobs.com/jobs/?page=1.

type object 'Bs4Config' has no attribute 'url'
Traceback (most recent call last):
  File "/Users/work/DevBox/JobsCrawler/src/crawlers/async_bs4.py", line 303, in async_bs4_crawl
    html = await fetch_func(session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/work/DevBox/JobsCrawler/src/crawler.py", line 101, in __fetch
    async with session.get(self.config.url, headers=random_user_agent) as response:
                           ^^^^^^^^^^^^^^^
AttributeError: type object 'Bs4Config' has no attribute 'url'
2024-07-09 19:45:16,948 - INFO - https://remote.co has started
2024-07-09 19:45:16,948 - DEBUG - All parameters for https://remote.co:
Bs4Config(name='https://remote.co', url='https://remote.co/international-remote-jobs/?page=', pages_to_crawl=1, start_point=1, strategy='container', follow_link='yes', inner_link_tag='.container.pt-4 .row.row-with-sidebar .col .card.mb-2 .card-body.loosen .single_job_listing .job_description', elements_path={'jobs_path': '.card.bg-light.mb-3.rounded-0 .card-body .card.bg-white.m-0 .card-body.p-0', 'title_path': '.card.m-0.border-left-0.border-right-0.border-top-0.border-bottom .card.border-0.p-3.job-card.bg-white .row.no-gutters.align-items-center .col.position-static .card-body.px-3.py-0.pl-md-0 .m-0 .font-weight-bold.larger', 'link_path': '.card.m-0.border-left-0.border-right-0.border-top-0.border-bottom', 'location_path': '.card.m-0.border-left-0.border-right-0.border-top-0.border-bottom .card.border-0.p-3.job-card.bg-white .row.no-gutters.align-items-center .col.position-static .card-body.px-3.py-0.pl-md-0 .m-0.text-secondary', 'description_path': '.card.m-0.border-left-0.border-right-0.border-top-0.border-bottom .card.border-0.p-3.job-card.bg-white .row.no-gutters.align-items-center .col.position-static .card-body.px-3.py-0.pl-md-0 .m-0.text-secondary'})
2024-07-09 19:45:16,948 - ERROR - AttributeError occurred before deploying crawling strategy on https://remote.co/international-remote-jobs/?page=1.

type object 'Bs4Config' has no attribute 'url'
Traceback (most recent call last):
  File "/Users/work/DevBox/JobsCrawler/src/crawlers/async_bs4.py", line 303, in async_bs4_crawl
    html = await fetch_func(session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/work/DevBox/JobsCrawler/src/crawler.py", line 101, in __fetch
    async with session.get(self.config.url, headers=random_user_agent) as response:
                           ^^^^^^^^^^^^^^^
AttributeError: type object 'Bs4Config' has no attribute 'url'
2024-07-09 19:45:16,949 - INFO - https://4dayweek.io has started
2024-07-09 19:45:16,949 - DEBUG - All parameters for https://4dayweek.io:
Bs4Config(name='https://4dayweek.io', url='https://4dayweek.io/remote-jobs/fully-remote/?page=', pages_to_crawl=1, start_point=1, strategy='container', follow_link='yes', inner_link_tag='.row.job-content-wrapper .col-sm-8.cols.hero-left', elements_path={'jobs_path': '.row.jobs-list', 'title_path': '.row.job-tile-title', 'link_path': '.row.job-tile-title h3 a', 'location_path': '.job-tile-tags .remote-country', 'description_path': '.job-tile-tags .tile-salary'})
2024-07-09 19:45:16,949 - ERROR - AttributeError occurred before deploying crawling strategy on https://4dayweek.io/remote-jobs/fully-remote/?page=1.

type object 'Bs4Config' has no attribute 'url'
Traceback (most recent call last):
  File "/Users/work/DevBox/JobsCrawler/src/crawlers/async_bs4.py", line 303, in async_bs4_crawl
    html = await fetch_func(session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/work/DevBox/JobsCrawler/src/crawler.py", line 101, in __fetch
    async with session.get(self.config.url, headers=random_user_agent) as response:
                           ^^^^^^^^^^^^^^^
AttributeError: type object 'Bs4Config' has no attribute 'url'
2024-07-09 19:45:16,949 - INFO - https://ai-jobs.net has started
2024-07-09 19:45:16,949 - DEBUG - All parameters for https://ai-jobs.net:
Bs4Config(name='https://ai-jobs.net', url='https://ai-jobs.net/?reg=', pages_to_crawl=7, start_point=7, strategy='container', follow_link='yes', inner_link_tag='#job-description', elements_path={'jobs_path': '.list-group.list-group-flush.mb-4', 'title_path': '.col.pt-2.pb-3 .h5.mb-2.text-body-emphasis', 'link_path': '.col.pt-2.pb-3', 'location_path': '.col.pt-2.pb-3 .float-end.text-end.text-body.d-inline-block.w-25.ms-2 .d-block.d-md-none.text-break', 'description_path': '.col.pt-2.pb-3 .badge.rounded-pill.text-bg-light'})
2024-07-09 19:45:16,950 - ERROR - AttributeError occurred before deploying crawling strategy on https://ai-jobs.net/?reg=7.

type object 'Bs4Config' has no attribute 'url'
Traceback (most recent call last):
  File "/Users/work/DevBox/JobsCrawler/src/crawlers/async_bs4.py", line 303, in async_bs4_crawl
    html = await fetch_func(session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/work/DevBox/JobsCrawler/src/crawler.py", line 101, in __fetch
    async with session.get(self.config.url, headers=random_user_agent) as response:
                           ^^^^^^^^^^^^^^^
AttributeError: type object 'Bs4Config' has no attribute 'url'
2024-07-09 19:45:16,955 - INFO - Finished bs4 crawlers. Results below ⬇︎
2024-07-09 19:45:17,470 - INFO - {"Total count of jobs before crawling": 85578, "Total number of unique jobs": 0, "Current total count of jobs in PostgreSQL": 85578}
2024-07-09 19:45:17,637 - INFO - Async BS4 crawlers finished! all in: 1.82 seconds.
2024-07-09 19:50:07,468 - DEBUG - Using selector: KqueueSelector
2024-07-09 19:50:08,568 - INFO - https://dribbble.com has started
2024-07-09 19:50:08,569 - DEBUG - All parameters for https://dribbble.com:
Bs4Config(name='https://dribbble.com', url='https://dribbble.com/jobs?anywhere=true&keyword=&page=', pages_to_crawl=1, start_point=1, strategy='main', follow_link='yes', inner_link_tag='.flushed .container-small.job-details-page-container .main-content-container .margin-t-16.job-details-description', elements_path={'jobs_path': '.job-list-item', 'title_path': '.job-details-container .job-title-company-container .job-title.job-board-job-title', 'link_path': '.job-link', 'location_path': '.job-additional-details-container .job-details .location-container.job-board-job-location', 'description_path': '.job-details-container .job-title-company-container .job-role'})
2024-07-09 19:50:08,569 - ERROR - AttributeError occurred before deploying crawling strategy on https://dribbble.com/jobs?anywhere=true&keyword=&page=1.

type object 'Bs4Config' has no attribute 'url'
Traceback (most recent call last):
  File "/Users/work/DevBox/JobsCrawler/src/crawlers/async_bs4.py", line 303, in async_bs4_crawl
    html = await fetch_func(session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/work/DevBox/JobsCrawler/src/crawler.py", line 101, in __fetch
    print(self.config.url)
          ^^^^^^^^^^^^^^^
AttributeError: type object 'Bs4Config' has no attribute 'url'
2024-07-09 19:50:08,572 - INFO - https://www.python.org has started
2024-07-09 19:50:08,572 - DEBUG - All parameters for https://www.python.org:
Bs4Config(name='https://www.python.org', url='https://www.python.org/jobs/?page=', pages_to_crawl=1, start_point=1, strategy='main', follow_link='yes', inner_link_tag='.content-wrapper .container .main-content.with-right-sidebar .text .job-description', elements_path={'jobs_path': '.list-recent-jobs.list-row-container.menu li', 'title_path': '.listing-company-name a', 'link_path': '.listing-company-name a', 'description_path': '.listing-job-type', 'location_path': '.listing-location a'})
2024-07-09 19:50:08,572 - ERROR - AttributeError occurred before deploying crawling strategy on https://www.python.org/jobs/?page=1.

type object 'Bs4Config' has no attribute 'url'
Traceback (most recent call last):
  File "/Users/work/DevBox/JobsCrawler/src/crawlers/async_bs4.py", line 303, in async_bs4_crawl
    html = await fetch_func(session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/work/DevBox/JobsCrawler/src/crawler.py", line 101, in __fetch
    print(self.config.url)
          ^^^^^^^^^^^^^^^
AttributeError: type object 'Bs4Config' has no attribute 'url'
2024-07-09 19:50:08,572 - INFO -  has started
2024-07-09 19:50:08,572 - DEBUG - All parameters for :
Bs4Config(name='', url='https://www.fossjobs.net/jobs-worldwide/?page=', pages_to_crawl=1, start_point=1, strategy='main', follow_link='yes', inner_link_tag='.container .columns .column.is-9 .box.content .job-description', elements_path={'jobs_path': '.container .columns .column.is-9 .box.content .post', 'title_path': 'h2 a', 'link_path': 'h2 a', 'location_path': '.media .media-content .content', 'description_path': '.media .media-content .content'})
2024-07-09 19:50:08,573 - ERROR - AttributeError occurred before deploying crawling strategy on https://www.fossjobs.net/jobs-worldwide/?page=1.

type object 'Bs4Config' has no attribute 'url'
Traceback (most recent call last):
  File "/Users/work/DevBox/JobsCrawler/src/crawlers/async_bs4.py", line 303, in async_bs4_crawl
    html = await fetch_func(session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/work/DevBox/JobsCrawler/src/crawler.py", line 101, in __fetch
    print(self.config.url)
          ^^^^^^^^^^^^^^^
AttributeError: type object 'Bs4Config' has no attribute 'url'
2024-07-09 19:50:08,573 - INFO - https://vuejobs.com has started
2024-07-09 19:50:08,573 - DEBUG - All parameters for https://vuejobs.com:
Bs4Config(name='https://vuejobs.com', url='https://vuejobs.com/jobs/?page=', pages_to_crawl=1, start_point=1, strategy='container', follow_link='yes', inner_link_tag='.lg\\:pb-12 .py-8.lg\\:py-12 .container .order-2.lg\\:order.lg\\:col-span-5 .prose.max-w-full.mt-6.prose-lg', elements_path={'jobs_path': '.grid.gap-y-4', 'title_path': 'a .flex.flex-col.justify-center.md\\:flex-row.md\\:justify-start.md\\:items-center .flex.items-center .ml-3', 'link_path': 'a', 'location_path': 'a .text-xs.mt-3.flex.gap-x-4.gap-y-1.flex-wrap.items-center.md\\:gap-2', 'description_path': 'a .text-xs.mt-3.flex.gap-x-4.gap-y-1.flex-wrap.items-center.md\\:gap-2'})
2024-07-09 19:50:08,573 - ERROR - AttributeError occurred before deploying crawling strategy on https://vuejobs.com/jobs/?page=1.

type object 'Bs4Config' has no attribute 'url'
Traceback (most recent call last):
  File "/Users/work/DevBox/JobsCrawler/src/crawlers/async_bs4.py", line 303, in async_bs4_crawl
    html = await fetch_func(session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/work/DevBox/JobsCrawler/src/crawler.py", line 101, in __fetch
    print(self.config.url)
          ^^^^^^^^^^^^^^^
AttributeError: type object 'Bs4Config' has no attribute 'url'
2024-07-09 19:50:08,573 - INFO - https://remote.co has started
2024-07-09 19:50:08,573 - DEBUG - All parameters for https://remote.co:
Bs4Config(name='https://remote.co', url='https://remote.co/international-remote-jobs/?page=', pages_to_crawl=1, start_point=1, strategy='container', follow_link='yes', inner_link_tag='.container.pt-4 .row.row-with-sidebar .col .card.mb-2 .card-body.loosen .single_job_listing .job_description', elements_path={'jobs_path': '.card.bg-light.mb-3.rounded-0 .card-body .card.bg-white.m-0 .card-body.p-0', 'title_path': '.card.m-0.border-left-0.border-right-0.border-top-0.border-bottom .card.border-0.p-3.job-card.bg-white .row.no-gutters.align-items-center .col.position-static .card-body.px-3.py-0.pl-md-0 .m-0 .font-weight-bold.larger', 'link_path': '.card.m-0.border-left-0.border-right-0.border-top-0.border-bottom', 'location_path': '.card.m-0.border-left-0.border-right-0.border-top-0.border-bottom .card.border-0.p-3.job-card.bg-white .row.no-gutters.align-items-center .col.position-static .card-body.px-3.py-0.pl-md-0 .m-0.text-secondary', 'description_path': '.card.m-0.border-left-0.border-right-0.border-top-0.border-bottom .card.border-0.p-3.job-card.bg-white .row.no-gutters.align-items-center .col.position-static .card-body.px-3.py-0.pl-md-0 .m-0.text-secondary'})
2024-07-09 19:50:08,573 - ERROR - AttributeError occurred before deploying crawling strategy on https://remote.co/international-remote-jobs/?page=1.

type object 'Bs4Config' has no attribute 'url'
Traceback (most recent call last):
  File "/Users/work/DevBox/JobsCrawler/src/crawlers/async_bs4.py", line 303, in async_bs4_crawl
    html = await fetch_func(session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/work/DevBox/JobsCrawler/src/crawler.py", line 101, in __fetch
    print(self.config.url)
          ^^^^^^^^^^^^^^^
AttributeError: type object 'Bs4Config' has no attribute 'url'
2024-07-09 19:50:08,574 - INFO - https://4dayweek.io has started
2024-07-09 19:50:08,574 - DEBUG - All parameters for https://4dayweek.io:
Bs4Config(name='https://4dayweek.io', url='https://4dayweek.io/remote-jobs/fully-remote/?page=', pages_to_crawl=1, start_point=1, strategy='container', follow_link='yes', inner_link_tag='.row.job-content-wrapper .col-sm-8.cols.hero-left', elements_path={'jobs_path': '.row.jobs-list', 'title_path': '.row.job-tile-title', 'link_path': '.row.job-tile-title h3 a', 'location_path': '.job-tile-tags .remote-country', 'description_path': '.job-tile-tags .tile-salary'})
2024-07-09 19:50:08,574 - ERROR - AttributeError occurred before deploying crawling strategy on https://4dayweek.io/remote-jobs/fully-remote/?page=1.

type object 'Bs4Config' has no attribute 'url'
Traceback (most recent call last):
  File "/Users/work/DevBox/JobsCrawler/src/crawlers/async_bs4.py", line 303, in async_bs4_crawl
    html = await fetch_func(session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/work/DevBox/JobsCrawler/src/crawler.py", line 101, in __fetch
    print(self.config.url)
          ^^^^^^^^^^^^^^^
AttributeError: type object 'Bs4Config' has no attribute 'url'
2024-07-09 19:50:08,575 - INFO - https://ai-jobs.net has started
2024-07-09 19:50:08,575 - DEBUG - All parameters for https://ai-jobs.net:
Bs4Config(name='https://ai-jobs.net', url='https://ai-jobs.net/?reg=', pages_to_crawl=7, start_point=7, strategy='container', follow_link='yes', inner_link_tag='#job-description', elements_path={'jobs_path': '.list-group.list-group-flush.mb-4', 'title_path': '.col.pt-2.pb-3 .h5.mb-2.text-body-emphasis', 'link_path': '.col.pt-2.pb-3', 'location_path': '.col.pt-2.pb-3 .float-end.text-end.text-body.d-inline-block.w-25.ms-2 .d-block.d-md-none.text-break', 'description_path': '.col.pt-2.pb-3 .badge.rounded-pill.text-bg-light'})
2024-07-09 19:50:08,575 - ERROR - AttributeError occurred before deploying crawling strategy on https://ai-jobs.net/?reg=7.

type object 'Bs4Config' has no attribute 'url'
Traceback (most recent call last):
  File "/Users/work/DevBox/JobsCrawler/src/crawlers/async_bs4.py", line 303, in async_bs4_crawl
    html = await fetch_func(session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/work/DevBox/JobsCrawler/src/crawler.py", line 101, in __fetch
    print(self.config.url)
          ^^^^^^^^^^^^^^^
AttributeError: type object 'Bs4Config' has no attribute 'url'
2024-07-09 19:50:08,580 - INFO - Finished bs4 crawlers. Results below ⬇︎
2024-07-09 19:50:09,094 - INFO - {"Total count of jobs before crawling": 85578, "Total number of unique jobs": 0, "Current total count of jobs in PostgreSQL": 85578}
2024-07-09 19:50:09,260 - INFO - Async BS4 crawlers finished! all in: 1.79 seconds.
2024-07-09 19:50:33,698 - DEBUG - Using selector: KqueueSelector
2024-07-09 19:50:34,785 - INFO - https://dribbble.com has started
2024-07-09 19:50:34,785 - DEBUG - All parameters for https://dribbble.com:
Bs4Config(name='https://dribbble.com', url='https://dribbble.com/jobs?anywhere=true&keyword=&page=', pages_to_crawl=1, start_point=1, strategy='main', follow_link='yes', inner_link_tag='.flushed .container-small.job-details-page-container .main-content-container .margin-t-16.job-details-description', elements_path={'jobs_path': '.job-list-item', 'title_path': '.job-details-container .job-title-company-container .job-title.job-board-job-title', 'link_path': '.job-link', 'location_path': '.job-additional-details-container .job-details .location-container.job-board-job-location', 'description_path': '.job-details-container .job-title-company-container .job-role'})
2024-07-09 19:50:34,785 - ERROR - AttributeError occurred before deploying crawling strategy on https://dribbble.com/jobs?anywhere=true&keyword=&page=1.

type object 'Bs4Config' has no attribute 'url'
Traceback (most recent call last):
  File "/Users/work/DevBox/JobsCrawler/src/crawlers/async_bs4.py", line 303, in async_bs4_crawl
    html = await fetch_func(session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/work/DevBox/JobsCrawler/src/crawler.py", line 102, in __fetch
    async with session.get(self.config.url, headers=random_user_agent) as response:
                           ^^^^^^^^^^^^^^^
AttributeError: type object 'Bs4Config' has no attribute 'url'
2024-07-09 19:50:34,786 - INFO - https://www.python.org has started
2024-07-09 19:50:34,786 - DEBUG - All parameters for https://www.python.org:
Bs4Config(name='https://www.python.org', url='https://www.python.org/jobs/?page=', pages_to_crawl=1, start_point=1, strategy='main', follow_link='yes', inner_link_tag='.content-wrapper .container .main-content.with-right-sidebar .text .job-description', elements_path={'jobs_path': '.list-recent-jobs.list-row-container.menu li', 'title_path': '.listing-company-name a', 'link_path': '.listing-company-name a', 'description_path': '.listing-job-type', 'location_path': '.listing-location a'})
2024-07-09 19:50:34,786 - ERROR - AttributeError occurred before deploying crawling strategy on https://www.python.org/jobs/?page=1.

type object 'Bs4Config' has no attribute 'url'
Traceback (most recent call last):
  File "/Users/work/DevBox/JobsCrawler/src/crawlers/async_bs4.py", line 303, in async_bs4_crawl
    html = await fetch_func(session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/work/DevBox/JobsCrawler/src/crawler.py", line 102, in __fetch
    async with session.get(self.config.url, headers=random_user_agent) as response:
                           ^^^^^^^^^^^^^^^
AttributeError: type object 'Bs4Config' has no attribute 'url'
2024-07-09 19:50:34,787 - INFO -  has started
2024-07-09 19:50:34,787 - DEBUG - All parameters for :
Bs4Config(name='', url='https://www.fossjobs.net/jobs-worldwide/?page=', pages_to_crawl=1, start_point=1, strategy='main', follow_link='yes', inner_link_tag='.container .columns .column.is-9 .box.content .job-description', elements_path={'jobs_path': '.container .columns .column.is-9 .box.content .post', 'title_path': 'h2 a', 'link_path': 'h2 a', 'location_path': '.media .media-content .content', 'description_path': '.media .media-content .content'})
2024-07-09 19:50:34,787 - ERROR - AttributeError occurred before deploying crawling strategy on https://www.fossjobs.net/jobs-worldwide/?page=1.

type object 'Bs4Config' has no attribute 'url'
Traceback (most recent call last):
  File "/Users/work/DevBox/JobsCrawler/src/crawlers/async_bs4.py", line 303, in async_bs4_crawl
    html = await fetch_func(session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/work/DevBox/JobsCrawler/src/crawler.py", line 102, in __fetch
    async with session.get(self.config.url, headers=random_user_agent) as response:
                           ^^^^^^^^^^^^^^^
AttributeError: type object 'Bs4Config' has no attribute 'url'
2024-07-09 19:50:34,787 - INFO - https://vuejobs.com has started
2024-07-09 19:50:34,788 - DEBUG - All parameters for https://vuejobs.com:
Bs4Config(name='https://vuejobs.com', url='https://vuejobs.com/jobs/?page=', pages_to_crawl=1, start_point=1, strategy='container', follow_link='yes', inner_link_tag='.lg\\:pb-12 .py-8.lg\\:py-12 .container .order-2.lg\\:order.lg\\:col-span-5 .prose.max-w-full.mt-6.prose-lg', elements_path={'jobs_path': '.grid.gap-y-4', 'title_path': 'a .flex.flex-col.justify-center.md\\:flex-row.md\\:justify-start.md\\:items-center .flex.items-center .ml-3', 'link_path': 'a', 'location_path': 'a .text-xs.mt-3.flex.gap-x-4.gap-y-1.flex-wrap.items-center.md\\:gap-2', 'description_path': 'a .text-xs.mt-3.flex.gap-x-4.gap-y-1.flex-wrap.items-center.md\\:gap-2'})
2024-07-09 19:50:34,788 - ERROR - AttributeError occurred before deploying crawling strategy on https://vuejobs.com/jobs/?page=1.

type object 'Bs4Config' has no attribute 'url'
Traceback (most recent call last):
  File "/Users/work/DevBox/JobsCrawler/src/crawlers/async_bs4.py", line 303, in async_bs4_crawl
    html = await fetch_func(session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/work/DevBox/JobsCrawler/src/crawler.py", line 102, in __fetch
    async with session.get(self.config.url, headers=random_user_agent) as response:
                           ^^^^^^^^^^^^^^^
AttributeError: type object 'Bs4Config' has no attribute 'url'
2024-07-09 19:50:34,788 - INFO - https://remote.co has started
2024-07-09 19:50:34,788 - DEBUG - All parameters for https://remote.co:
Bs4Config(name='https://remote.co', url='https://remote.co/international-remote-jobs/?page=', pages_to_crawl=1, start_point=1, strategy='container', follow_link='yes', inner_link_tag='.container.pt-4 .row.row-with-sidebar .col .card.mb-2 .card-body.loosen .single_job_listing .job_description', elements_path={'jobs_path': '.card.bg-light.mb-3.rounded-0 .card-body .card.bg-white.m-0 .card-body.p-0', 'title_path': '.card.m-0.border-left-0.border-right-0.border-top-0.border-bottom .card.border-0.p-3.job-card.bg-white .row.no-gutters.align-items-center .col.position-static .card-body.px-3.py-0.pl-md-0 .m-0 .font-weight-bold.larger', 'link_path': '.card.m-0.border-left-0.border-right-0.border-top-0.border-bottom', 'location_path': '.card.m-0.border-left-0.border-right-0.border-top-0.border-bottom .card.border-0.p-3.job-card.bg-white .row.no-gutters.align-items-center .col.position-static .card-body.px-3.py-0.pl-md-0 .m-0.text-secondary', 'description_path': '.card.m-0.border-left-0.border-right-0.border-top-0.border-bottom .card.border-0.p-3.job-card.bg-white .row.no-gutters.align-items-center .col.position-static .card-body.px-3.py-0.pl-md-0 .m-0.text-secondary'})
2024-07-09 19:50:34,788 - ERROR - AttributeError occurred before deploying crawling strategy on https://remote.co/international-remote-jobs/?page=1.

type object 'Bs4Config' has no attribute 'url'
Traceback (most recent call last):
  File "/Users/work/DevBox/JobsCrawler/src/crawlers/async_bs4.py", line 303, in async_bs4_crawl
    html = await fetch_func(session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/work/DevBox/JobsCrawler/src/crawler.py", line 102, in __fetch
    async with session.get(self.config.url, headers=random_user_agent) as response:
                           ^^^^^^^^^^^^^^^
AttributeError: type object 'Bs4Config' has no attribute 'url'
2024-07-09 19:50:34,788 - INFO - https://4dayweek.io has started
2024-07-09 19:50:34,788 - DEBUG - All parameters for https://4dayweek.io:
Bs4Config(name='https://4dayweek.io', url='https://4dayweek.io/remote-jobs/fully-remote/?page=', pages_to_crawl=1, start_point=1, strategy='container', follow_link='yes', inner_link_tag='.row.job-content-wrapper .col-sm-8.cols.hero-left', elements_path={'jobs_path': '.row.jobs-list', 'title_path': '.row.job-tile-title', 'link_path': '.row.job-tile-title h3 a', 'location_path': '.job-tile-tags .remote-country', 'description_path': '.job-tile-tags .tile-salary'})
2024-07-09 19:50:34,788 - ERROR - AttributeError occurred before deploying crawling strategy on https://4dayweek.io/remote-jobs/fully-remote/?page=1.

type object 'Bs4Config' has no attribute 'url'
Traceback (most recent call last):
  File "/Users/work/DevBox/JobsCrawler/src/crawlers/async_bs4.py", line 303, in async_bs4_crawl
    html = await fetch_func(session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/work/DevBox/JobsCrawler/src/crawler.py", line 102, in __fetch
    async with session.get(self.config.url, headers=random_user_agent) as response:
                           ^^^^^^^^^^^^^^^
AttributeError: type object 'Bs4Config' has no attribute 'url'
2024-07-09 19:50:34,789 - INFO - https://ai-jobs.net has started
2024-07-09 19:50:34,789 - DEBUG - All parameters for https://ai-jobs.net:
Bs4Config(name='https://ai-jobs.net', url='https://ai-jobs.net/?reg=', pages_to_crawl=7, start_point=7, strategy='container', follow_link='yes', inner_link_tag='#job-description', elements_path={'jobs_path': '.list-group.list-group-flush.mb-4', 'title_path': '.col.pt-2.pb-3 .h5.mb-2.text-body-emphasis', 'link_path': '.col.pt-2.pb-3', 'location_path': '.col.pt-2.pb-3 .float-end.text-end.text-body.d-inline-block.w-25.ms-2 .d-block.d-md-none.text-break', 'description_path': '.col.pt-2.pb-3 .badge.rounded-pill.text-bg-light'})
2024-07-09 19:50:34,789 - ERROR - AttributeError occurred before deploying crawling strategy on https://ai-jobs.net/?reg=7.

type object 'Bs4Config' has no attribute 'url'
Traceback (most recent call last):
  File "/Users/work/DevBox/JobsCrawler/src/crawlers/async_bs4.py", line 303, in async_bs4_crawl
    html = await fetch_func(session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/work/DevBox/JobsCrawler/src/crawler.py", line 102, in __fetch
    async with session.get(self.config.url, headers=random_user_agent) as response:
                           ^^^^^^^^^^^^^^^
AttributeError: type object 'Bs4Config' has no attribute 'url'
2024-07-09 19:50:34,793 - INFO - Finished bs4 crawlers. Results below ⬇︎
2024-07-09 19:50:35,317 - INFO - {"Total count of jobs before crawling": 85578, "Total number of unique jobs": 0, "Current total count of jobs in PostgreSQL": 85578}
2024-07-09 19:50:35,485 - INFO - Async BS4 crawlers finished! all in: 1.79 seconds.
2024-07-09 19:51:36,222 - DEBUG - Using selector: KqueueSelector
2024-07-09 19:51:37,322 - INFO - https://dribbble.com has started
2024-07-09 19:51:37,323 - DEBUG - All parameters for https://dribbble.com:
Bs4Config(name='https://dribbble.com', url='https://dribbble.com/jobs?anywhere=true&keyword=&page=', pages_to_crawl=1, start_point=1, strategy='main', follow_link='yes', inner_link_tag='.flushed .container-small.job-details-page-container .main-content-container .margin-t-16.job-details-description', elements_path={'jobs_path': '.job-list-item', 'title_path': '.job-details-container .job-title-company-container .job-title.job-board-job-title', 'link_path': '.job-link', 'location_path': '.job-additional-details-container .job-details .location-container.job-board-job-location', 'description_path': '.job-details-container .job-title-company-container .job-role'})
2024-07-09 19:51:37,323 - ERROR - AttributeError occurred before deploying crawling strategy on https://dribbble.com/jobs?anywhere=true&keyword=&page=1.

type object 'Bs4Config' has no attribute 'name'
Traceback (most recent call last):
  File "/Users/work/DevBox/JobsCrawler/src/crawlers/async_bs4.py", line 303, in async_bs4_crawl
    html = await fetch_func(session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/work/DevBox/JobsCrawler/src/crawler.py", line 101, in __fetch
    print(self.config.name)
          ^^^^^^^^^^^^^^^^
AttributeError: type object 'Bs4Config' has no attribute 'name'
2024-07-09 19:51:37,325 - INFO - https://www.python.org has started
2024-07-09 19:51:37,325 - DEBUG - All parameters for https://www.python.org:
Bs4Config(name='https://www.python.org', url='https://www.python.org/jobs/?page=', pages_to_crawl=1, start_point=1, strategy='main', follow_link='yes', inner_link_tag='.content-wrapper .container .main-content.with-right-sidebar .text .job-description', elements_path={'jobs_path': '.list-recent-jobs.list-row-container.menu li', 'title_path': '.listing-company-name a', 'link_path': '.listing-company-name a', 'description_path': '.listing-job-type', 'location_path': '.listing-location a'})
2024-07-09 19:51:37,325 - ERROR - AttributeError occurred before deploying crawling strategy on https://www.python.org/jobs/?page=1.

type object 'Bs4Config' has no attribute 'name'
Traceback (most recent call last):
  File "/Users/work/DevBox/JobsCrawler/src/crawlers/async_bs4.py", line 303, in async_bs4_crawl
    html = await fetch_func(session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/work/DevBox/JobsCrawler/src/crawler.py", line 101, in __fetch
    print(self.config.name)
          ^^^^^^^^^^^^^^^^
AttributeError: type object 'Bs4Config' has no attribute 'name'
2024-07-09 19:51:37,326 - INFO -  has started
2024-07-09 19:51:37,326 - DEBUG - All parameters for :
Bs4Config(name='', url='https://www.fossjobs.net/jobs-worldwide/?page=', pages_to_crawl=1, start_point=1, strategy='main', follow_link='yes', inner_link_tag='.container .columns .column.is-9 .box.content .job-description', elements_path={'jobs_path': '.container .columns .column.is-9 .box.content .post', 'title_path': 'h2 a', 'link_path': 'h2 a', 'location_path': '.media .media-content .content', 'description_path': '.media .media-content .content'})
2024-07-09 19:51:37,326 - ERROR - AttributeError occurred before deploying crawling strategy on https://www.fossjobs.net/jobs-worldwide/?page=1.

type object 'Bs4Config' has no attribute 'name'
Traceback (most recent call last):
  File "/Users/work/DevBox/JobsCrawler/src/crawlers/async_bs4.py", line 303, in async_bs4_crawl
    html = await fetch_func(session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/work/DevBox/JobsCrawler/src/crawler.py", line 101, in __fetch
    print(self.config.name)
          ^^^^^^^^^^^^^^^^
AttributeError: type object 'Bs4Config' has no attribute 'name'
2024-07-09 19:51:37,326 - INFO - https://vuejobs.com has started
2024-07-09 19:51:37,326 - DEBUG - All parameters for https://vuejobs.com:
Bs4Config(name='https://vuejobs.com', url='https://vuejobs.com/jobs/?page=', pages_to_crawl=1, start_point=1, strategy='container', follow_link='yes', inner_link_tag='.lg\\:pb-12 .py-8.lg\\:py-12 .container .order-2.lg\\:order.lg\\:col-span-5 .prose.max-w-full.mt-6.prose-lg', elements_path={'jobs_path': '.grid.gap-y-4', 'title_path': 'a .flex.flex-col.justify-center.md\\:flex-row.md\\:justify-start.md\\:items-center .flex.items-center .ml-3', 'link_path': 'a', 'location_path': 'a .text-xs.mt-3.flex.gap-x-4.gap-y-1.flex-wrap.items-center.md\\:gap-2', 'description_path': 'a .text-xs.mt-3.flex.gap-x-4.gap-y-1.flex-wrap.items-center.md\\:gap-2'})
2024-07-09 19:51:37,327 - ERROR - AttributeError occurred before deploying crawling strategy on https://vuejobs.com/jobs/?page=1.

type object 'Bs4Config' has no attribute 'name'
Traceback (most recent call last):
  File "/Users/work/DevBox/JobsCrawler/src/crawlers/async_bs4.py", line 303, in async_bs4_crawl
    html = await fetch_func(session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/work/DevBox/JobsCrawler/src/crawler.py", line 101, in __fetch
    print(self.config.name)
          ^^^^^^^^^^^^^^^^
AttributeError: type object 'Bs4Config' has no attribute 'name'
2024-07-09 19:51:37,327 - INFO - https://remote.co has started
2024-07-09 19:51:37,327 - DEBUG - All parameters for https://remote.co:
Bs4Config(name='https://remote.co', url='https://remote.co/international-remote-jobs/?page=', pages_to_crawl=1, start_point=1, strategy='container', follow_link='yes', inner_link_tag='.container.pt-4 .row.row-with-sidebar .col .card.mb-2 .card-body.loosen .single_job_listing .job_description', elements_path={'jobs_path': '.card.bg-light.mb-3.rounded-0 .card-body .card.bg-white.m-0 .card-body.p-0', 'title_path': '.card.m-0.border-left-0.border-right-0.border-top-0.border-bottom .card.border-0.p-3.job-card.bg-white .row.no-gutters.align-items-center .col.position-static .card-body.px-3.py-0.pl-md-0 .m-0 .font-weight-bold.larger', 'link_path': '.card.m-0.border-left-0.border-right-0.border-top-0.border-bottom', 'location_path': '.card.m-0.border-left-0.border-right-0.border-top-0.border-bottom .card.border-0.p-3.job-card.bg-white .row.no-gutters.align-items-center .col.position-static .card-body.px-3.py-0.pl-md-0 .m-0.text-secondary', 'description_path': '.card.m-0.border-left-0.border-right-0.border-top-0.border-bottom .card.border-0.p-3.job-card.bg-white .row.no-gutters.align-items-center .col.position-static .card-body.px-3.py-0.pl-md-0 .m-0.text-secondary'})
2024-07-09 19:51:37,327 - ERROR - AttributeError occurred before deploying crawling strategy on https://remote.co/international-remote-jobs/?page=1.

type object 'Bs4Config' has no attribute 'name'
Traceback (most recent call last):
  File "/Users/work/DevBox/JobsCrawler/src/crawlers/async_bs4.py", line 303, in async_bs4_crawl
    html = await fetch_func(session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/work/DevBox/JobsCrawler/src/crawler.py", line 101, in __fetch
    print(self.config.name)
          ^^^^^^^^^^^^^^^^
AttributeError: type object 'Bs4Config' has no attribute 'name'
2024-07-09 19:51:37,328 - INFO - https://4dayweek.io has started
2024-07-09 19:51:37,328 - DEBUG - All parameters for https://4dayweek.io:
Bs4Config(name='https://4dayweek.io', url='https://4dayweek.io/remote-jobs/fully-remote/?page=', pages_to_crawl=1, start_point=1, strategy='container', follow_link='yes', inner_link_tag='.row.job-content-wrapper .col-sm-8.cols.hero-left', elements_path={'jobs_path': '.row.jobs-list', 'title_path': '.row.job-tile-title', 'link_path': '.row.job-tile-title h3 a', 'location_path': '.job-tile-tags .remote-country', 'description_path': '.job-tile-tags .tile-salary'})
2024-07-09 19:51:37,328 - ERROR - AttributeError occurred before deploying crawling strategy on https://4dayweek.io/remote-jobs/fully-remote/?page=1.

type object 'Bs4Config' has no attribute 'name'
Traceback (most recent call last):
  File "/Users/work/DevBox/JobsCrawler/src/crawlers/async_bs4.py", line 303, in async_bs4_crawl
    html = await fetch_func(session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/work/DevBox/JobsCrawler/src/crawler.py", line 101, in __fetch
    print(self.config.name)
          ^^^^^^^^^^^^^^^^
AttributeError: type object 'Bs4Config' has no attribute 'name'
2024-07-09 19:51:37,328 - INFO - https://ai-jobs.net has started
2024-07-09 19:51:37,328 - DEBUG - All parameters for https://ai-jobs.net:
Bs4Config(name='https://ai-jobs.net', url='https://ai-jobs.net/?reg=', pages_to_crawl=7, start_point=7, strategy='container', follow_link='yes', inner_link_tag='#job-description', elements_path={'jobs_path': '.list-group.list-group-flush.mb-4', 'title_path': '.col.pt-2.pb-3 .h5.mb-2.text-body-emphasis', 'link_path': '.col.pt-2.pb-3', 'location_path': '.col.pt-2.pb-3 .float-end.text-end.text-body.d-inline-block.w-25.ms-2 .d-block.d-md-none.text-break', 'description_path': '.col.pt-2.pb-3 .badge.rounded-pill.text-bg-light'})
2024-07-09 19:51:37,328 - ERROR - AttributeError occurred before deploying crawling strategy on https://ai-jobs.net/?reg=7.

type object 'Bs4Config' has no attribute 'name'
Traceback (most recent call last):
  File "/Users/work/DevBox/JobsCrawler/src/crawlers/async_bs4.py", line 303, in async_bs4_crawl
    html = await fetch_func(session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/work/DevBox/JobsCrawler/src/crawler.py", line 101, in __fetch
    print(self.config.name)
          ^^^^^^^^^^^^^^^^
AttributeError: type object 'Bs4Config' has no attribute 'name'
2024-07-09 19:51:37,333 - INFO - Finished bs4 crawlers. Results below ⬇︎
2024-07-09 19:51:37,830 - INFO - {"Total count of jobs before crawling": 85578, "Total number of unique jobs": 0, "Current total count of jobs in PostgreSQL": 85578}
2024-07-09 19:51:37,987 - INFO - Async BS4 crawlers finished! all in: 1.77 seconds.
